### ISSUE TITLE
TypeORM repository.update does not provide the ID in afterUpdate

### ISSUE THREAD

**Issue by radulescuandrew** [anchan828/typeorm-helpers#1084]
Using the simple `repository.update` throws error on `createHistory` because the original ID is missing.

Somehow I avoided this problem until now, or I am missing something in the current implementation (using typeorm 0.3.6).

Debugging your `createHistory` method, it seems that the `entity` param in `afterUpdate` is missing the ID and obviously will set it to undefined here:

```
const originalID = Reflect.get(history, primaryColumn.propertyName);
Reflect.set(history, originalIdPropertyName, originalID);
```

There are lots of topics discussing the drawbacks of using `update` instead of `save`, but I already lost a couple of hours debugging this and it may be worth to be mentioned. 

What are your thoughts on this @anchan828 ?

**Comment by anchan828** [comment]
Hi @radulescuandrew, `save` automatically reacquires the entity, so you can get the ID, but `update` does not.
If you want `update` to work, you need to retrieve the entity in the Subscriber, but it is better not to do so by design.

**Comment by radulescuandrew** [comment]
Hi @anchan828, yea I got it, the hard way unfortunately.

Would you mind updating the docs with a short disclaimer?

**Comment by anchan828** [comment]
Added https://github.com/anchan828/typeorm-helpers/commit/ab09e3fa7b5ad3c9ae9499b41b4fde6bf67e7172
Sorry for the confusion.

**Comment by radulescuandrew** [comment]
Much appreciated, I'll close it now.
