### ISSUE TITLE
Author column

### ISSUE THREAD

**Issue by JonatanColussi** [anchan828/typeorm-helpers#1129]
### Discussed in https://github.com/anchan828/typeorm-helpers/discussions/1108

<div type='discussions-op-text'>

<sup>Originally posted by **JonatanColussi** October 27, 2022</sup>
Hi, i need add the author of the action in my history table. what is the better way to do it?</div>

**Comment by anchan828** [comment]
Hi, Sorry, I already don't use and don't maintain the history package. So I removed the package. I can't state clearly, but if you search for a similar package, you might try to use that one.　Thanks for using it.
