### ISSUE TITLE
Prefixing and Relations on history columns

### ISSUE THREAD

**Issue by harveyappleton** [anchan828/typeorm-helpers#651]
Hey @anchan828 

Wondering if this might be worth doing:

- `originalID` --> `history_original_id`, and also make this a relational field (if possible) back to the original entity's `id` column?
- `action` --> `history_action` (helps reduce possible clashes with the original entity, as I could see `action` being a valid column for an entity?)
- Add in a `history_timestamp` or `history_logged_at` column - which is the timestamp at which that entry was added?

Let me know your thoughts! :)

**Comment by anchan828** [comment]
Hi @harveyappleton,

That's a good idea. In order to cope with this, I think that there are some breaking changes.
I'll figure out how to solve that.

**Comment by anchan828** [comment]
so... For backward compatibility as well, we would create new HistoryEntity and HistorySubscriber.

**Comment by harveyappleton** [comment]
ok sounds cool! What are you thinking of naming the new entities/subscribers?
The `history_logged_at` could be a `@CreateDateColumn()` so it will auto-populate.

**Comment by anchan828** [comment]
> ok sounds cool! What are you thinking of naming the new entities/subscribers?

I can't think of a good name for it. 🤣 

> The history_logged_at could be a @CreateDateColumn() so it will auto-populate.

Yeah, so this package will not support history_logged_at column. you can easily define it.

--- 

Maybe just adding a decorator for HistoryOriginalIdColumn might help.
If there is no HistoryOriginalIdColumn, then use originalID (I will output warning log)

```ts
@Entity()
class TestHistoryEntity extends TestEntity 
  // HistoryEntityInterface will no longer be available.
  // implements HistoryEntityInterface 
{
  // You can use any property name you like.
  @HistoryOriginalIdColumn()
  public history_originalID!: number;

  // You can rename column name
  @HistoryActionColumn({ name: "history_action" })
  public action!: HistoryActionType;

  @CreateDateColumn({ name: "history_logged_at" })
  public timestamp: Date;
}
```

OK
```ts
@Entity()
class TestEntity {
  @PrimaryGeneratedColumn()
  public id!: number;
}

@Entity()
class TestHistoryEntity extends TestEntity 
{
  @Column()
  public originalID!: number;

  @HistoryActionColumn()
  public action!: HistoryActionType;
}
```

**Comment by anchan828** [comment]
Created PR #653 (Still WIP.)

A relational field is difficult, because the entity may have been deleted after the delete action, which will cause an error.
Please define it manually if you need to. 🙏

**Comment by anchan828** [comment]
Published https://www.npmjs.com/package/@anchan828/typeorm-history/v/0.5.0 🎉

**Comment by harveyappleton** [comment]
Amazing thanks @anchan828 ! 👍
