### ISSUE TITLE
Deleted entities not tracked in history

### ISSUE THREAD

**Issue by harveyappleton** [anchan828/typeorm-helpers#661]
When an entity is soft deleted, the history log does not show this.

(See point 5 on this comment for more info on soft delete event behaviour: [https://github.com/typeorm/typeorm/issues/534#issuecomment-535416895](https://github.com/typeorm/typeorm/issues/534#issuecomment-535416895))

**Comment by harveyappleton** [comment]
Actually, I'm not sure the delete behaviour is working at all... trying to replicate, will let you know

**Comment by harveyappleton** [comment]
In fact, I don't think any delete event (soft or normal) are being logged. It appears as tho created and updated are fine though.

**Comment by harveyappleton** [comment]
OK updates:

1. Calling `.delete()` or `.softDelete()` **does not** emit an action that history can subscribe to, hence the history log not showing this. Calling `.remove()` or `.softRemove()` **does** emit an action.

2. Calling `.softRemove()` actually emits an _update_ action, not a _delete_ action. (See comment linked above). Not sure how you want to handle this @anchan828 ? If someone were to perform: `create entity -> soft delete it -> recover it` - what should history log show? `CREATED, UPDATED, UPDATED`? or `CREATED, DELETED, RECOVERED`?

**Comment by anchan828** [comment]
Hi @harveyappleton,

> 1

The history pacakge supports ActiveRecord patterns. `.delete()` and `.softDelete()` are for manager and repository patterns, right?
At the moment, I can't support this unless the Subscriber can also pass entities via delete and softDelete 😔.

> 2

 I can't support this unless the Subscriber can also pass delete date object...
https://github.com/typeorm/typeorm/issues/6327

**Comment by harveyappleton** [comment]
1. It seems to be working for me, and I am using repository pattern **not** ActiveRecord pattern, so that's good! I think the `.delete()` and `.softDelete()` methods don't emit events, but the remove equivalents do.. here's an excerpt from the typescript definition files for the entity manager:
```/**
     * Deletes entities by a given condition(s).
     * Unlike save method executes a primitive operation without cascades, relations and other operations included.
     * Executes fast and efficient DELETE query.
     * Does not check if entity exist in the database.
     * Condition(s) cannot be empty.
     */
```

2. Ah ok, for now then I guess it can only be `CREATED, UPDATED, UPDATED` until we can get the `deleted_at` column value into the subscriber?

**Comment by anchan828** [comment]
Thanks for the info.

1. My understanding is that Delete only deletes by a given condition, so it may not hold the entity. What this means is that you may have to use `.find` to get the entity to create the History from original entity.

2. Maybe yes. You can create an UPDATED event, but I think the deleted_at will be saved as null.

**Comment by anchan828** [comment]
Solving this problem seems to be very difficult. I can’t come up with any good ideas, So I may need to change my perspective. 🤔

**Comment by anchan828** [comment]
Hi, Sorry, I already don't use and don't maintain the history package. So I removed the package. I can't state clearly, but if you search for a similar package, you might try to use that one.　Thanks for using it.
