### ISSUE TITLE
Prevent TypeORM from generating constraints

### ISSUE THREAD

**Issue by radulescuandrew** [anchan828/typeorm-helpers#751]
Hello,

This is not an issue with the lib, which is well written and achieves the main goal.

There is any way to inform TypeORM to avoid creating any constraints for an (extended) entity instead of dropping the indices later? I am thinking about a decorator/property that I'm missing, similar to [avoiding foreign key constraint creation](https://typeorm.io/#/relations-faq/avoid-foreign-key-constraint-creation).

By extending an Entity I will inherit of course all the constraints which I don't want to manage. A simple solution would be not to extend but copy all the properties in the History class but this will result in maintaining two entities for each history table, which again, I don't fancy and that's one of the reasons I'm using this lib. 

The main issue I'm trying to avoid is that generating migrations will always include the constraints and also in a dev environment  automatic synchronization (`schema:sync`) will not work anymore.

Thanks!

**Comment by anchan828** [comment]
Hi @radulescuandrew, Thanks for your feedback.

> There is any way to inform TypeORM to avoid creating any constraints for an (extended) entity instead of dropping the indices later?

I'm struggling with this too...

It would be nice if there was some kind of hook to customize `schema:sync`, but at least I don't know how to do that.　After much deliberation, I implemented the [dropUniqueIndices](https://github.com/anchan828/typeorm-helpers/blob/master/packages/history/src/history-migration.ts#L13) function　😔

I would appreciate it if you could let me know if you have any information that would be very helpful.

**Comment by radulescuandrew** [comment]
@anchan828 For now I'm just using an abstract entity to keep them in sync without the constraints and I also asked the question [here](https://stackoverflow.com/questions/70151755/prevent-typeorm-from-generating-constraints) on SO, maybe we find something in the near future.

Thanks for your time!
