### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by asijoumi** [anchan828/typeorm-helpers#791]
Hi !

When I want to save many entities in one action, I have this exception thrown : `RangeError: Maximum call stack size exceeded`.
I think is due to some recursion in the implementation but I'm not sure.

2 examples :

This one is saving the entities without the history, but an exception is thrown inside the anonymous function : `QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.`
```ts
await getConnection().transaction(transactionalEntityManager => {
    transactionalEntityManager.save(firstEntity);
    transactionalEntityManager.save(secondEntity);
    return Promise.resolve();
});
```

This one crashed : `RangeError: Maximum call stack size exceeded`
```ts
await getConnection().transaction(transactionalEntityManager => {
    await transactionalEntityManager.save(firstEntity);
    await transactionalEntityManager.save(secondEntity);
});
```

I'm pretty sure this is due the history mode, but I don't know why exactly

**Comment by anchan828** [comment]
Hi @asijoumi 

Can I get more information? I tested it with a very simple code and it was fine. 
https://github.com/anchan828/typeorm-helpers/blob/736ad813fc2ba30f33bbdfff44c7205c0ab0ff42/packages/history/src/e2e-tests/issue-791.spec-e2e.ts#L79-L84

CI: https://github.com/anchan828/typeorm-helpers/runs/4740215197?check_suite_focus=true

Probably some complex reason such as relation or many nested entities may be causing this problem.

**Comment by anchan828** [comment]
> This one is saving the entities without the history, but an exception is thrown inside the anonymous function : QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.

I'm not sure if this is the answer, but from the error message and the sample code, it seems that the reason is that there is no await attached.


```ts
await getConnection().transaction(transactionalEntityManager => {
    transactionalEntityManager.save(firstEntity);
    transactionalEntityManager.save(secondEntity);
    return Promise.resolve();
});
```
↓
```ts
await getConnection().transaction(transactionalEntityManager => {
    await transactionalEntityManager.save([firstEntity, secondEntity]);
});
```

**Comment by asijoumi** [comment]
Thanks @anchan828 for answering. 

I have some dependencies, here is the example :

```ts
const books: Array<Book> = await getRepository(Book)
    ...
    .getMany();

const firstBook: Book = books.find((p) => ...);
const firstPage: Page = firstBook.pages[0];

const secondBook = books.find((p) => ...);
const secondPage: Page = secondBook.pages[0];

// This is a fake example
firstPage.book = secondBook;
secondPage.book = firstBook;

await getConnection().transaction(async transactionalEntityManager => {
    await transactionalEntityManager.save([firstPage, secondPage]);
});
```

In my example, the `Book` entity has also an history table.
So I think the subscriber try to save the `Page`(s) and also the `Book`(s), but crashed.

**Comment by asijoumi** [comment]
This is the exception : 

```
RangeError: Maximum call stack size exceeded
    at Arguments.values (<anonymous>)
    ...
    at EntityMetadata.create (/usr/src/app/node_modules/typeorm/metadata/EntityMetadata.js:251:19)
    at /usr/src/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:61:87
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:54:40
    at Array.forEach (<anonymous>)
    at PlainObjectToNewEntityTransformer.groupAndTransform (/usr/src/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:42:32)
    at /usr/src/app/node_modules/typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js:81:27
    at Array.forEach (<anonymous>)
    ```

**Comment by asijoumi** [comment]
This is due to circular dependency : `.../typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js`

Inside this part of `groupAndTransform` : 

```js
if (metadata.relations.length) {
    metadata.relations.forEach(function (relation) {
        ...
    });
```

**Comment by asijoumi** [comment]
@anchan828  no problem, thank you for answering.

What do you mean by :
> disabling the automatic definition of relations 

You mean changing the table schema ?

I saw the code in the TypeORM package. But, without the history subscriber, the entities saved perfectly.

**Comment by asijoumi** [comment]
Do you want a full example project ?

**Comment by anchan828** [comment]
Hi @asijoumi

A sample would be helpful, but I think this is a problem with the subscriber specification, so it may be difficult to solve.

Creating an independent History table that does not inherit from the Entity may solve the problem. What happens if you remove the `pages` property from the Book entity?
https://github.com/anchan828/typeorm-helpers/issues/779#issuecomment-1007523637

**Comment by asijoumi** [comment]
There is the code for the sample example of this issue : 
https://github.com/asijoumi/typeorm-demo

> Creating an independent History table that does not inherit from the Entity may solve the problem. What happens if you remove the pages property from the Book entity?

It will be difficult to maintain all off the attributes of the Book class and BookHistoryClass.

**Comment by anchan828** [comment]
@asijoumi Thanks for creating the repository! I'll check it out tonight.

**Comment by anchan828** [comment]
@asijoumi My first approach
https://github.com/anchan828/typeorm-demo/commit/e962a42817281cc86a3453ff4f8817c0b4b2ff88

> It will be difficult to maintain all off the attributes of the Book class and BookHistoryClass.

Inheriting the Book class as an interface makes it relatively easy to maintain.

```ts
export class BookHistory extends BaseEntity implements Omit<Book,  keyof BaseEntity | "pages">, HistoryEntityInterface {}
```

**Comment by anchan828** [comment]
Passed test (you need to use latest @anchan828/typeorm-history package). 
https://github.com/anchan828/typeorm-demo/runs/4801220475?check_suite_focus=true

**Comment by asijoumi** [comment]
It works, no exception thrown.

See the result : 

|id |nb_words                     |page_number|technical_index                              |originalID|action |bookId|
|---|-----------------------------|-----------|---------------------------------------------|----------|-------|------|
|1  |0                            |0          |0                                            |1         |CREATED|NULL  |
|2  |2                            |1          |1                                            |2         |CREATED|NULL  |
|3  |4                            |2          |2                                            |3         |CREATED|NULL  |
|4  |0                            |0          |0                                            |4         |CREATED|NULL  |
|5  |2                            |1          |1                                            |5         |CREATED|NULL  |
|6  |4                            |2          |2                                            |6         |CREATED|NULL  |
|7  |0                            |0          |0                                            |7         |CREATED|NULL  |
|8  |2                            |1          |1                                            |8         |CREATED|NULL  |
|9  |4                            |2          |2                                            |9         |CREATED|NULL  |
|10 |0                            |0          |0                                            |1         |UPDATED|NULL  |
|11 |0                            |0          |0                                            |4         |UPDATED|NULL  |

The bookId is not saved.

**Comment by anchan828** [comment]
ah... You can set the bookId by using hooks.

https://github.com/anchan828/typeorm-demo/commit/186e0cd434b5877a41eedb2263a1ec0930ec4f9c#diff-977cda47a02c819639972d264c2becd94528ed374b85fb1510bb454faf81941bR19-R41

However, I think this is redundant and not a very good design.
I'll do some more research.

**Comment by anchan828** [comment]
@asijoumi Can you try to re-create the Book entity? It appears to be working well.
https://github.com/anchan828/typeorm-demo/commit/1ddbeb8837763ac005600fadde94b8709361fb28

I'm reverting all my changes, just regenerating Entity.
https://github.com/anchan828/typeorm-demo/commit/27691cfcc55936d940a8ecb1b211d7693390c5c5

**Comment by anchan828** [comment]
If it is an Entity retrieved by relation, there is probably some metadata or something left, and it looks like it is doing something bad.

**Comment by asijoumi** [comment]
> Can you try to re-create the Book entity? It appears to be working well.
anchan828/typeorm-demo@1ddbeb8

It works !!! 

```sql
query: SELECT `book`.`id` AS `book_id`, `book`.`author` AS `book_author`, `book`.`name` AS `book_name`, `book`.`technical_index` AS `book_technical_index`, `page`.`id` AS `page_id`, `page`.`nb_words` AS `page_nb_words`, `page`.`page_number` AS `page_page_number`, `page`.`technical_index` AS `page_technical_index`, `page`.`bookId` AS `page_bookId` FROM `book` `book` LEFT JOIN `page` `page` ON `book`.`id` = page.bookid
Get books
Switching pages from books
query: START TRANSACTION
Try to save
query: SELECT `Page`.`id` AS `Page_id`, `Page`.`nb_words` AS `Page_nb_words`, `Page`.`page_number` AS `Page_page_number`, `Page`.`technical_index` AS `Page_technical_index`, `Page`.`bookId` AS `Page_bookId` FROM `page` `Page` WHERE `Page`.`id` IN (?, ?) -- PARAMETERS: [1,4]
query: UPDATE `page` SET `bookId` = ? WHERE `id` IN (?) -- PARAMETERS: [2,1]
query: UPDATE `page` SET `bookId` = ? WHERE `id` IN (?) -- PARAMETERS: [1,4]
query: INSERT INTO `page_history`(`id`, `nb_words`, `page_number`, `technical_index`, `originalID`, `action`, `bookId`) VALUES (DEFAULT, ?, ?, ?, ?, ?, ?) -- PARAMETERS: [0,0,0,1,"UPDATED",2]
query: INSERT INTO `page_history`(`id`, `nb_words`, `page_number`, `technical_index`, `originalID`, `action`, `bookId`) VALUES (DEFAULT, ?, ?, ?, ?, ?, ?) -- PARAMETERS: [0,0,0,4,"UPDATED",1]
query: SELECT `PageHistory`.`id` AS `PageHistory_id`, `PageHistory`.`action` AS `PageHistory_action` FROM `page_history` `PageHistory` WHERE `PageHistory`.`id` = ? -- PARAMETERS: [10]
query: SELECT `PageHistory`.`id` AS `PageHistory_id`, `PageHistory`.`action` AS `PageHistory_action` FROM `page_history` `PageHistory` WHERE `PageHistory`.`id` = ? -- PARAMETERS: [11]
Saved
query: COMMIT
```

How can we explain that ? Is that `create` method doesn't use nested element ?

**Comment by asijoumi** [comment]
> If it is an Entity retrieved by relation, there is probably some metadata or something left, and it looks like it is doing something bad.

I think this due to the forEach method in the `typeorm` package

**Comment by asijoumi** [comment]
![Diagramme vierge](https://user-images.githubusercontent.com/25631702/149331298-59a0895c-ca70-4718-8102-820a809267ef.jpeg)

I think we can see the problem with this schema.
Switching the pages from books creates some circular dependencies.

And, in the typeorm package, we have : 

> https://github.com/typeorm/typeorm/blob/master/src/query-builder/transformer/PlainObjectToNewEntityTransformer.ts#L44

**Comment by anchan828** [comment]
> How can we explain that ? Is that create method doesn't use nested element ?

Yes, Since Book and Page have the same circular dependencies, we have to stop the circular dependencies by creating a new object.

**Comment by asijoumi** [comment]
Ok thanks for all. I'll we try to change my code and add `create` method before each assignment.
