### ISSUE TITLE
ManyToMany relationships using incorrect column names

### ISSUE THREAD

**Issue by lukemovement** [anchan828/typeorm-helpers#900]
Environment:
    "@anchan828/typeorm-history": "^1.0.1",
    "@nestjs/common": "^8.4.4",
    "@nestjs/core": "^8.4.4",
    "@nestjs/typeorm": "^9.0.0-next.2",
    "typeorm": "0.3.6",

When using a ManyToMany columns, `History` is added to the column name in the database, however, this is not reflected when an update to an entity is made as the manager provided looks for the original column name.

```ts
class Entity1 extends BaseEntity {
  @ManyToMany(() => Entity2, (entity2: Entity2) => entity2.entities1)
  @JoinTable()
  public entities2: Array<Entity2>;
}

class Entity2 extends BaseEntity {
  @ManyToMany(() => Entity1, (entity1: Entity1) => entity2.entities2)
  public entities1: Array<Entity1>;
}
```

The join table for the above classes many to many relation will includes the columns named `entity1Id` and `entity2Id`. The history table for this will includes columns named columns named `entity1HistoryId` and `entity2Id`.

A workaround for this issue is defining joinColumn.name inside of the **JoinTable** declaration as `entity1Id`. 

My assumption for this issue is that the removal of the ormconfig.json has resulted in the source code being the primary source of information about the structure as apposed to the database being using as the primary source of information.

I've managed to track the issue to this line so far: https://github.com/anchan828/typeorm-helpers/blob/43592ae881e6a1b71d59ab8c12150c41235148b2/packages/history/src/history-subscriber.ts#L169

**Comment by anchan828** [comment]
Hi @lukemovement,

This is an unintended behavior whereby the creation of a history entity by inheriting from the Entity1 entity automatically generates the table used by ManyToMany. This package does not support tables generated by ManyToMany.
