### ISSUE TITLE
Adding more columns

### ISSUE THREAD

**Issue by gmmkmtgk** [anchan828/typeorm-helpers#955]
How can we change the source code to add more columns 
like time of addition

**Comment by anchan828** [comment]
Hi, Your question is about history package?

You can handle it with basic typeorm usage.
```
@Entity()
class TestHistoryEntity extends BaseEntity implements HistoryEntityInterface<TestEntity> {
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column()
  public test!: string;

  @Column()
  public new_column!: string;

 
  @HistoryOriginalIdColumn()
  public history_originalID!: number;

  @HistoryActionColumn({ name: "history_action" })
  public action!: HistoryActionType;
}
```

**Comment by gmmkmtgk** [comment]
could please also tell the significance of ! 
code runs Wells without it also
like id! and id 

Thankful to you for making this library

**Comment by gmmkmtgk** [comment]
> Hi, Your question is about history package?
> 
> You can handle it with basic typeorm usage.
> 
> ```
> @Entity()
> class TestHistoryEntity extends BaseEntity implements HistoryEntityInterface<TestEntity> {
>   @PrimaryGeneratedColumn()
>   public id!: number;
> 
>   @Column()
>   public test!: string;
> 
>   @Column()
>   public new_column!: string;
> 
>  
>   @HistoryOriginalIdColumn()
>   public history_originalID!: number;
> 
>   @HistoryActionColumn({ name: "history_action" })
>   public action!: HistoryActionType;
> }
> ```

Followed as you told me 
But facing this issue
<img width="676" alt="image" src="https://user-images.githubusercontent.com/51493190/172563050-7380c1c8-dfc0-47cf-bd72-07383ba692b0.png">
Updated at should not get value when we createthe user. This time of creation should be their util we delete the user.
But created at and updated at takes the same vaue of current time when any action is taken place on the user 

code 

@Entity()
export class TestHistoryEntity extends BaseEntity implements HistoryEntityInterface<Client> {
  @PrimaryGeneratedColumn()
  public id: number;

  @Column()
  public test: string;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;

  // You can use any property name you like.
  @HistoryOriginalIdColumn()
  public history_originalID!: number;

  // You can rename column name
  @HistoryActionColumn({ name: "history_action" })
  public action!: HistoryActionType;
}

**Comment by anchan828** [comment]
`!` is Non-null assertion operator.

Isn't this because CreateDateColumn and UpdateDateColumn are defined in HistoryTable?
That is the correct behavior since this history mechanism creates a new entity.

The base entity should have those columns and the History entity should have just a datetime column.

```ts
@Entity()
class TestEntity extends BaseEntity {
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column()
  public test!: string;

  @CreateDateColumn()
  created_at: Date;

  @UpdateDateColumn()
  updated_at: Date;
}
```

```ts
@Entity()
class TestHistoryEntity extends BaseEntity implements HistoryEntityInterface<TestEntity> {
  @PrimaryGeneratedColumn()
  public id!: number;

  @Column()
  public test!: string;

  @Column({ type: "datetime" })
  created_at: Date;

  @Column({ type: "datetime" })
  updated_at: Date;
 
  @HistoryOriginalIdColumn()
  public history_originalID!: number;

  @HistoryActionColumn({ name: "history_action" })
  public action!: HistoryActionType;

}
```

**Comment by anchan828** [comment]
Please create an issue if you have any more questions!
